[tool.poetry]
name = "gflabel"
version = "0.1.0"
description = ""
authors = ["Nicholas Devenish <ndevenish@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
build123d = "^0.5.0"
rich = "^13.7.1"

[tool.poetry.scripts]
gflabel = "gflabel.cli:run"

[tool.jane]
profiles = ["default"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
unfixable = ["F841"]

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# [tool.bumpversion]
# current_version = "0.1.0"
[tool.bumpversion]
current_version = "0.1.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
# regex = false
# ignore_missing_version = false
# ignore_missing_files = false
tag = false
# sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
# allow_dirty = false
commit = false
message = "Bump version: {current_version} → {new_version}"
# commit_args = ""
